---
# Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: self-release-ui-test
  namespace: yunwei
subsets:
  - addresses:
      - ip: 192.168.10.234
    ports:
      - port: 8081

# Service
---
kind: Service
apiVersion: v1
metadata:
  name: self-release-ui-test
  namespace: yunwei
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: self-release-ui-test
  namespace: yunwei
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: auth
spec:
  rules:
    - host: projects-test.newops.haodai.net
      http:
        paths:
          - path: /
            backend:
              serviceName: self-release-ui-test
              servicePort: 80
